### ISSUE TITLE
SWF not visible

### ISSUE THREAD

**Issue by acidpoison** [terrytheplatypus/celibatesam2#1]
I was having BHD try it out
He's saying that on part 1 (terry's part - stencyl), it just shows a black screen
means that the stencyl game wasn't displaying
However, when linked to just the game flash file, it works fine. wtf
Firefox (newest he claims) and Windows XP

**Comment by terrytheplatypus** [comment]
i dunno, maybe you accidentally changed the link but kept the same thing in the stencyl project

**Comment by acidpoison** [comment]
@terrytheplatypus Can you try to re-export the project as a file smaller than 1mb? I want to try to use [Swiffy](https://developers.google.com/swiffy/) to convert it to HTML5 to avoid browser conflicts.
